sources:
  - EmeryCubic.glyphs
axisOrder:
  - wght
  - ital
familyName: Emery Cubic
buildOTF: false
buildTTF: false
buildStatic: false
buildWebfont: false
buildVariable: true
stat:
  - name: Weight
    tag: wght
    values:
    - name: Hairline
      value: 50
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
    - name: ExtraBlack
      value: 1000
  - name: Length
    tag: LENG
    values:
    - name: Normal
      value: 1
    - name: Long
      value: 1000
  - name: Sharpness
    tag: SHRP
    values:
    - name: Normal
      value: 1
    - name: Sharp
      value: 1000
